name: 📝 Development Workflow
on:
  - push
jobs:
  test:
    name: 🔍 Testing
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
      - name: 💣 Run some tests
        run: npm run test

  lint:
    name: ⬣ Linting
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
      - name: ✨ Code format check
        run: npx prettier --check .
      - name: ✅ Typecheck
        run: npm run typecheck

  deploy:
    name: 🛳 Deploying
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
      - name: 📦 Build the app
        run: npm run build
      - name: 🔥 Publish
        run: npx wrangler deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
